services:
  # FastAPI Web Service
  - type: web
    name: morningmaghreb-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: REDIS_URL
        sync: false

  # Background Worker for ETL Jobs
  - type: worker
    name: morningmaghreb-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A etl.celery_app worker --loglevel=info
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false

databases:
  - name: morningmaghreb-db
    databaseName: morningmaghreb
    user: morningmaghreb_user 